// Adaptación editorial del banco fanmade a español neutro latinoamericano.
// Se conservan los scores y la estructura; sólo se reemplazan giros
// castellanos o poco naturales fuera de Latinoamérica.
const TEXT_REPLACEMENTS = new Map([
  ["¡Es pronto para rendirse!", "¡Todavía es muy pronto para rendirse!"],
  ["De los que estudian a diario", "De los que estudian todos los días"],
  ["De los que estudian si se acuerdan", "De los que estudian cuando se acuerdan"],
  ["De los que estudian lo justo", "De los que estudian sólo lo necesario"],
  ["Voy a necesitar ayuda...", "Voy a necesitar ayuda…"],
  ["La hago sin rechistar", "La hago sin quejarme"],
  ["Que la haga otro", "Que la haga alguien más"],
  ["Por supuesto", "Claro que sí"],
  ["¿Te disculpas siempre de todo corazón?", "¿Siempre te disculpas de corazón?"],
  ["¿Estudias con regularidad?", "¿Estudias con frecuencia?"],
  ["¡Lo mío es el deporte!", "¡Lo mío es hacer deporte!"],
  ["Se rumorea que hay un fantasma en los servicios de la escuela. ¿Qué haces?", "Se rumorea que hay un fantasma en los baños de la escuela. ¿Qué haces?"],
  ["Imagina que todos habéis tomado postre y todavía queda una porción. ¿Qué haces?", "Imagina que todos ya comieron postre y todavía queda una porción. ¿Qué haces?"],
  ["A ver si no se dan cuenta...", "A ver si nadie se da cuenta…"],
  ["La echamos a suertes", "Lo sorteamos"],
  ["¡Tonto el último!", "¡El último pierde!"],
  ["¡A toda pastilla!", "¡A toda velocidad!"],
  ["Como una rosa", "Como si nada"],
  ["Les sigo el rollo", "Les sigo la corriente"],
  ["Lo muestro haciéndole más caso", "Lo demuestro prestándole más atención"],
  ["Evidente, le tomo un poco el pelo", "Obviamente, lo molesto un poco"],
  ["¡Lo grito a los cuatro vientos!", "¡Lo grito a todo pulmón!"],
  ["¿Te gustan las fiestas con marcha?", "¿Te gustan las fiestas animadas?"],
  ["Paso...", "No, gracias…"],
  ["Le están cantando cumpleaños feliz a alguien de la mesa de al lado. ¿Qué haces?", "Le están cantando “Feliz cumpleaños” a alguien de la mesa de al lado. ¿Qué haces?"],
  ["Me marcho", "Me voy"],
  ["Hago oídos sordos...", "Finjo no escuchar…"],
  ["¿Prefieres jugar fuera de casa en lugar de dentro?", "¿Prefieres jugar afuera en vez de adentro?"],
  ["Ves una cama que tiene pinta de ser muy cómoda. Lo primero que haces es...", "Ves una cama que parece muy cómoda. Lo primero que haces es…"],
  ["Imagina que descubres un cofre hecho polvo en medio de unas ruinas. ¿Qué haces?", "Imagina que encuentras un cofre en muy mal estado en medio de unas ruinas. ¿Qué haces?"],
  ["Un amigo tropieza y se cae estrepitosamente. ¿Qué haces?", "Un amigo tropieza y cae de manera aparatosa. ¿Qué haces?"],
  ["Estás soñando despierto... y un amigo te tira agua encima. ¿Qué haces?", "Estás distraído… y un amigo te echa agua encima. ¿Qué haces?"],
  ["¿Se te ha pasado por la cabeza alguna vez que pueda haber un tesoro enterrado en tu jardín?", "¿Alguna vez pensaste que podría haber un tesoro enterrado en tu jardín?"],
  ["¡Síii!", "¡Sííí!"],
  ["¿Has contado alguna vez un chiste sin ninguna gracia?", "¿Alguna vez contaste un chiste sin ninguna gracia?"],
  ["¡Eh! ¡Mira!... ¡Hay alguien detrás de ti! ¿Te has girado para mirar?", "¡Oye, mira!... ¡Hay alguien detrás de ti! ¿Te diste la vuelta para mirar?"],
  ["¡Anda que menudo susto!", "¡Qué susto!"],
  ["Lo reconozco, me has engañado", "Lo reconozco, me engañaste"],
  ["Para nada, no me la has colado", "Para nada, no me engañaste"],
  ["Tu amigo acaba de preparar una comida que sabe a rayos. Cuando te pregunta qué te parece, ¿qué le dices?", "Tu amigo acaba de preparar una comida que sabe horrible. Cuando te pregunta qué te parece, ¿qué le dices?"],
  ["Mmm, ¿qué... rico!", "Mmm… ¿qué? ¡Está rico!"],
  ["Te encuentras con alguien que hacía mucho tiempo que no veías. ¿Qué haces?", "Te encuentras con alguien a quien no veías desde hace mucho tiempo. ¿Qué haces?"],
  ["Mantengo una conversación trivial", "Hago conversación"],
  ["Tengo buenas y malas noticias... ¿Cuáles quieres que te cuente primero?", "Tengo buenas y malas noticias… ¿Cuál quieres escuchar primero?"],
  ["¿Alguna vez te has dado cuenta de que estabas monopolizando una conversación?", "¿Alguna vez notaste que estabas dominando una conversación?"],
  ["Si ves un botón, ¿te entran deseos irrefrenables de pulsarlo?", "Si ves un botón, ¿te dan ganas irresistibles de presionarlo?"],
  ["¡Te encuentras algo con una rebaja espectacular! ¿Qué haces?", "¡Encuentras algo con un descuento increíble! ¿Qué haces?"],
  ["¡Me lo compro ipso facto!", "¡Lo compro de inmediato!"],
  ["Pienso si de verdad me hace falta", "Pienso si de verdad lo necesito"],
  ["Pido una rebaja mayor", "Pido un descuento aún mayor"],
  ["Estás guardando la merienda para ir de excursión y te entra el hambre. ¿Qué haces?", "Estás guardando la comida para ir de excursión y te da hambre. ¿Qué haces?"],
  ["Me como un poco", "Como un poco"],
  ["Me aguanto y lo guardo todo", "Me aguanto y guardo todo"],
  ["¿Qué merienda? ¡Me la he zampado!", "¿Qué comida? ¡Me la comí toda!"],
  ["¿Te gustaría ser una persona alta algún día?", "¿Te gustaría ser más alto algún día?"],
  ["¡Y tanto!", "¡Claro que sí!"],
  ["¿Te has mirado alguna vez en un espejo y has pensado: \"¡Cómo molo!\"?", "¿Alguna vez te miraste al espejo y pensaste: \"¡Qué genial me veo!\"?"],
  ["¡Cómo molo!", "¡Qué genial!"],
  ["¿Serías capaz de regañar a alguien que has visto hacer algo mal?", "¿Serías capaz de llamar la atención a alguien que viste hacer algo mal?"],
  ["Estás a punto de comprar un juego que te gusta un montón cuando alguien se te adelanta y se lleva el último de la tienda. ¿Cómo te sienta?", "Estás a punto de comprar un juego que te gusta mucho cuando alguien se adelanta y se lleva el último de la tienda. ¿Cómo te sientes?"],
  ["¡Qué va a ser de mí!", "¡¿Qué voy a hacer ahora?!"],
  ["Ayer compraste un juguete y hoy vuelves a la tienda y te lo encuentras a mitad de precio. ¿Cómo te sienta?", "Ayer compraste un juguete y hoy regresas a la tienda y lo ves a mitad de precio. ¿Cómo te sientes?"],
  ["¡Qué rabia!", "¡Qué enojo!"],
  ["Has quedado con un amigo y llega tarde. ¿Qué te parece?", "Quedaste con un amigo y llega tarde. ¿Qué te parece?"],
  ["Mal", "Me molesta"],
  ["Te acabas de pegar un buen atracón y traen el postre. ¿Qué haces?", "Acabas de comer demasiado y traen el postre. ¿Qué haces?"],
  ["Digo que no. ¡Engorda demasiado!", "Digo que no. ¡Tiene demasiadas calorías!"],
  ["Te han invitado a una fiesta fenomenal, ¿pero cuando llegas no hay nadie! ¿Qué piensas?", "Te invitaron a una fiesta increíble, pero cuando llegas no hay nadie. ¿Qué piensas?"],
  ["No me enteré bien de la fecha", "Entendí mal la fecha"],
  ["¿Eres de los que piensan que, pase lo que pase, la vida sigue?", "¿Piensas que, pase lo que pase, la vida sigue?"],
  ["Todo el rato", "Siempre"],
  ["¿Suena el teléfono! ¿Qué haces?", "¡Suena el teléfono! ¿Qué haces?"],
  ["Respondo de inmediato", "Contesto de inmediato"],
  ["Parece que tus amigos están quedando para salir, pero no alcanzas a oírlos. ¿Qué piensas?", "Parece que tus amigos están haciendo planes para salir, pero no logras escucharlos. ¿Qué piensas?"],
  ["Te han dado una gran bolsa de recuerdo. ¿Qué haces?", "Te dieron una gran bolsa de regalo. ¿Qué haces?"],
  ["¡La agito!", "¡La sacudo!"],
  ["¿Se te ha olvidado en alguna ocasión que habías comprado algo y has vuelto a comprar exactamente lo mismo?", "¿Alguna vez olvidaste que habías comprado algo y volviste a comprar exactamente lo mismo?"],
  ["¿Eres de las personas que no cambian de opinión una vez que han decidido algo?", "¿Eres de las personas que no cambian de opinión después de decidir algo?"],
  ["¿Le has dicho alguna vez \"Es un placer conocerte\" a alguna persona que ya conocías?", "¿Alguna vez le dijiste \"Es un placer conocerte\" a alguien que ya conocías?"],
  ["¿Has hecho algún propósito de año nuevo?", "¿Alguna vez hiciste un propósito de Año Nuevo?"],
  ["¡Qué va!", "¡Para nada!"],
  ["¿Crees que es mejor llegar siempre algo tarde a una fiesta?", "¿Crees que es mejor llegar siempre un poco tarde a una fiesta?"],
  ["¡Te ha tocado el premio gordo en una rifa! ¿Qué piensas?", "¡Te ganaste el premio mayor en una rifa! ¿Qué piensas?"],
  ["¡Cómo mola!", "¡Qué genial!"],
  ["Ayer jugabais tan felices, pero hoy tu amigo no te habla. ¿Qué ha pasado?", "Ayer estaban jugando felices, pero hoy tu amigo no te habla. ¿Qué pasó?"],
  ["Igual está enfermo", "Tal vez está enfermo"],
  ["Estará preocupado por algo", "Tal vez está preocupado por algo"],
  ["Te quitas las zapatillas y te das cuenta de que llevas dos calcetines diferentes. ¿Qué haces?", "Te quitas los zapatos y notas que llevas dos calcetines diferentes. ¿Qué haces?"],
  ["¿¿Otra vez??", "¿Otra vez?"],
  ["Acabas de meter la pata hasta el fondo. Todos tus amigos se han dado cuenta y están enfadados contigo. ¿Qué haces?", "Acabas de cometer un error grave. Todos tus amigos se dieron cuenta y están molestos contigo. ¿Qué haces?"],
  ["¡Me marcho a todo gas!", "¡Me voy a toda velocidad!"],
  ["¿Has llamado alguna vez por error \"mamá\" o \"papá\" a alguno de tus profesores?", "¿Alguna vez llamaste por error \"mamá\" o \"papá\" a alguno de tus profesores?"],
  ["¿Has dicho algo alguna vez sin pensar primero en las consecuencias?", "¿Alguna vez dijiste algo sin pensar primero en las consecuencias?"],
  ["Estás en clase y te entran ganas de ir al baño. ¿Qué haces?", "Estás en clase y te dan ganas de ir al baño. ¿Qué haces?"],
  ["Me escaqueo", "Salgo sin avisar"],
  ["Espero hasta que acabe la clase", "Espero hasta que termine la clase"],
  ["Un amigo te quiere invitar a cenar. ¿Qué haces?", "Un amigo te invita a cenar. ¿Qué haces?"],
  ["Ves un pastel caducado, pero solo por un día. ¿Qué haces?", "Ves un pastel que venció hace sólo un día. ¿Qué haces?"],
  ["Estás cenando en un restaurante de cinco tenedores. ¿Qué plato pides?", "Estás cenando en un restaurante elegante. ¿Qué plato pides?"],
  ["¡Un filete, por supuesto!", "¡Un plato de carne, claro!"],
]);

export function adaptQuizToLatam(data) {
  for (const question of data.questions ?? []) {
    question.title = TEXT_REPLACEMENTS.get(question.title) ?? question.title;
    for (const response of question.responses ?? []) response.response = TEXT_REPLACEMENTS.get(response.response) ?? response.response;
  }
  return data;
}
